### ISSUE TITLE
创建管理员报错

### ISSUE THREAD

**Issue by BA7IEE** [nineaiyu/xadmin-server#6]
`(.venv) dengwang@dengwangs-MacBook-Pro xadmin-server % python manage.py createsuperuser
System check identified some issues:

WARNINGS:
system.DataPermission.menu: (fields.W340) null has no effect on ManyToManyField.
system.DeptInfo.roles: (fields.W340) null has no effect on ManyToManyField.
system.DeptInfo.rules: (fields.W340) null has no effect on ManyToManyField.
system.FieldPermission.field: (fields.W340) null has no effect on ManyToManyField.
system.Menu.model: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_dept: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_role: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_user: (fields.W340) null has no effect on ManyToManyField.
system.UserInfo.roles: (fields.W340) null has no effect on ManyToManyField.
system.UserInfo.rules: (fields.W340) null has no effect on ManyToManyField.
system.UserRole.menu: (fields.W340) null has no effect on ManyToManyField.
Username: adminn
Email address: ad@aa.cn 
Password: 
Password (again): 
Traceback (most recent call last):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/manage.py", line 22, in <module>
    main()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 89, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 238, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/contrib/auth/models.py", line 172, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/contrib/auth/models.py", line 155, in _create_user
    user.save(using=self._db)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/system/utils/signal_handler.py", line 171, in clean_cache_handler
    invalid_user_cache(instance.pk)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/system/utils/signal_handler.py", line 110, in invalid_user_cache
    cache_response.invalid_cache(f'UserInfoView_retrieve_{user_pk}')
  File "/Users/dengwang/Code/Python/gene/xadmin-server/common/base/magic.py", line 215, in invalid_cache
    for delete_key in cache.iter_keys(cache_key):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django_redis/client/default.py", line 688, in iter_keys
    for item in client.scan_iter(match=pattern, count=itersize):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 3051, in scan_iter
    cursor, data = self.scan(
                   ^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 3026, in scan
    return self.execute_command("SCAN", *pieces, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/client.py", line 540, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 288, in connect
    self.on_connect()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 354, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
(.venv) dengwang@dengwangs-MacBook-Pro xadmin-server % 

`

**Comment by nineaiyu** [comment]
看下配置文件，连接 redis 的配置是否正常

**Comment by BA7IEE** [comment]
> 看下配置文件，连接 redis 的配置是否正常

谢谢，问题解决了，REDIS的密码和路径问题
