### ISSUE TITLE
导入菜单报错

### ISSUE THREAD

**Issue by BA7IEE** [nineaiyu/xadmin-server#7]
(.venv) dengwang@dengwangs-MacBook-Pro xadmin-server % python manage.py load_init_json
System check identified some issues:

WARNINGS:
system.DataPermission.menu: (fields.W340) null has no effect on ManyToManyField.
system.DeptInfo.roles: (fields.W340) null has no effect on ManyToManyField.
system.DeptInfo.rules: (fields.W340) null has no effect on ManyToManyField.
system.FieldPermission.field: (fields.W340) null has no effect on ManyToManyField.
system.Menu.model: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_dept: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_role: (fields.W340) null has no effect on ManyToManyField.
system.NoticeMessage.notice_user: (fields.W340) null has no effect on ManyToManyField.
system.UserInfo.roles: (fields.W340) null has no effect on ManyToManyField.
system.UserInfo.rules: (fields.W340) null has no effect on ManyToManyField.
system.UserRole.menu: (fields.W340) null has no effect on ManyToManyField.
Traceback (most recent call last):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/manage.py", line 22, in <module>
    main()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/system/management/commands/load_init_json.py", line 34, in handle
    super(Command, self).handle(*fixture_labels, **options)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
       ^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/core/serializers/base.py", line 265, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/system/utils/signal_handler.py", line 134, in clean_cache_handler
    cache_response.invalid_cache('MenuView_list_*')
  File "/Users/dengwang/Code/Python/gene/xadmin-server/common/base/magic.py", line 215, in invalid_cache
    for delete_key in cache.iter_keys(cache_key):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/django_redis/client/default.py", line 688, in iter_keys
    for item in client.scan_iter(match=pattern, count=itersize):
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 3051, in scan_iter
    cursor, data = self.scan(
                   ^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/commands/core.py", line 3026, in scan
    return self.execute_command("SCAN", *pieces, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/client.py", line 540, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 288, in connect
    self.on_connect()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 354, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/Users/dengwang/Code/Python/gene/xadmin-server/.venv/lib/python3.11/site-packages/redis/_parsers/socket.py", line 68, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Problem installing fixture '/Users/dengwang/Code/Python/gene/xadmin-server/loadjson/menu.json': Connection closed by server.
(.venv) dengwang@dengwangs-MacBook-Pro xadmin-server %

**Comment by BA7IEE** [comment]
thank you


> redis 连接不正常，检查下redis是否正常
